# Generated by two-phase-flake. Regen with: nix run .#bootstrap
{
  description = "Two-phase flake: synthetic thin eval collects inputs, bootstrap materializes a real flake";
  outputs =
    flakeInputs:
    let
      lib = flakeInputs.nixpkgs.lib;
      importTree = import flakeInputs.import-tree;

      # Thin eval: collect input declarations (only forces pure data)
      thinEval = lib.evalModules {
        modules = [
          flakeInputs.flake-file.flakeModules.flake
          (importTree ./modules)
        ];
      };

      declared = thinEval.config.flake-file.inputs;

      # Resolve inputs: real flake inputs win, fetchTree fallback from lock
      allInputs = import ./resolve.nix {
        inherit lib flakeInputs;
        lockFile = ./inputs.lock;
        declaredInputs = declared;
      };

      # Full eval with all resolved inputs
      fullEval = lib.evalModules {
        specialArgs = {
          inputs = allInputs;
          inherit (allInputs) self;
        };
        modules = [
          flakeInputs.flake-file.flakeModules.flake
          (importTree ./modules)
        ];
      };

      moduleOutputs = fullEval.config.flake-outputs;

      # Bootstrap: materialize flake.nix with real inputs for the external interface
      flakeFileLib = import "${flakeInputs.flake-file}/dev/modules/_lib" lib;
      inherit (flakeFileLib) inputsExpr nixCode;

      resolvedInputs = thinEval.config.flake-file.preProcess (
        inputsExpr thinEval.config.flake-file.inputs
      );

      flakeSource =
        let
          desc = lib.escape [ "\"" "\\" ] (thinEval.config.flake-file.description or "");
          inputsBody = nixCode {
            expr = resolvedInputs;
            styles = [
              { attrSep = "\n    "; }
              { attrSep = "\n      "; }
            ];
          };
        in
        ''
          # Generated by two-phase-flake. Regen with: nix run .#bootstrap
          {
            description = "${desc}";
            outputs = ${builtins.readFile ./outputs-expr.nix};
            inputs = ${inputsBody};
          }
        '';

      eachSystem = lib.genAttrs [
        "x86_64-linux"
        "aarch64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];

      bootstrapApp =
        system:
        let
          pkgs = flakeInputs.nixpkgs.legacyPackages.${system};
          flakeFile = pkgs.writeText "flake-source.nix" flakeSource;
        in
        {
          type = "app";
          program = lib.getExe (
            pkgs.writeShellApplication {
              name = "bootstrap";
              runtimeInputs = [ pkgs.nixfmt-rfc-style ];
              text = ''
                cp ${flakeFile} flake.nix
                nixfmt flake.nix
                echo "flake.nix materialized. Next: nix flake lock"
              '';
            }
          );
        };

      # Lock manager: writes inputs.lock from current flake.lock / resolved state
      lockApp =
        system:
        let
          pkgs = flakeInputs.nixpkgs.legacyPackages.${system};

          # Build lock entries for inputs not in seed
          seedNames = [
            "nixpkgs"
            "import-tree"
            "flake-file"
          ];
          extraDeclared = lib.filterAttrs (n: _: !lib.elem n seedNames) declared;

          lockEntries = lib.mapAttrs (
            name: _spec:
            let
              src = allInputs.${name} or null;
            in
            if src == null then
              null
            else
              {
                flake = _spec.flake or true;
                locked = {
                  type = "github";
                  owner = _spec.owner or "";
                  repo = _spec.repo or "";
                  rev = src.rev or "";
                  narHash = src.narHash or "";
                };
                follows = lib.mapAttrs (_: sub: sub.follows or null) (
                  lib.filterAttrs (_: sub: sub.follows or null != null) (_spec.inputs or { })
                );
              }
          ) extraDeclared;

          lockJson = builtins.toJSON (lib.filterAttrs (_: v: v != null) lockEntries);
          lockFile = pkgs.writeText "inputs-lock.json" lockJson;
        in
        {
          type = "app";
          program = lib.getExe (
            pkgs.writeShellApplication {
              name = "update-lock";
              runtimeInputs = [ pkgs.jq ];
              text = ''
                jq . ${lockFile} > inputs.lock
                echo "inputs.lock updated."
              '';
            }
          );
        };
    in
    moduleOutputs
    // {
      apps = lib.recursiveUpdate (moduleOutputs.apps or { }) (
        eachSystem (system: {
          bootstrap = bootstrapApp system;
          update-lock = lockApp system;
        })
      );
    };
  inputs = {
    flake-file.url = "github:vic/flake-file";
    flake-parts = {
      inputs.nixpkgs-lib.follows = "nixpkgs";
      url = "github:hercules-ci/flake-parts";
    };
    home-manager = {
      inputs.nixpkgs.follows = "nixpkgs";
      url = "github:nix-community/home-manager";
    };
    import-tree = {
      flake = false;
      url = "github:vic/import-tree";
    };
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
  };
}
