# Generated by two-phase-flake bootstrap. Regen with: nix run .#bootstrap
{
  outputs =
    inputs:
    let
      importTree = import inputs.import-tree;
    in
    (inputs.nixpkgs.lib.evalModules {
      specialArgs = {
        inherit inputs;
        inherit (inputs) self;
      };
      modules = [
        (importTree ./modules)
        ./_bootstrap/options.nix
      ];
    }).config.outputs;

  inputs = {
    flake-parts.url = "github:hercules-ci/flake-parts";
    flake-parts.inputs.nixpkgs-lib.follows = "nixpkgs";
    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";
    import-tree.url = "github:vic/import-tree";
    import-tree.flake = false;
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
  };
}
