inputs:
  let
    lib = inputs.nixpkgs.lib;
    importTree = import inputs.import-tree;

    eval = lib.evalModules {
      specialArgs = {
        inherit inputs;
        inherit (inputs) self;
      };
      modules = [
        inputs.flake-file.flakeModules.flake
        (importTree ./modules)
      ];
    };

    # Use flake-outputs (raw attrset) not flake-file's outputs (submodule-wrapped)
    moduleOutputs = eval.config.flake-outputs;

    # Bootstrap: re-materialize flake.nix from module declarations
    flakeFileLib = import "${inputs.flake-file}/dev/modules/_lib" lib;
    inherit (flakeFileLib) inputsExpr nixCode;

    resolvedInputs = eval.config.flake-file.preProcess (
      inputsExpr eval.config.flake-file.inputs
    );

    flakeSource =
      let
        desc = lib.escape [ "\"" "\\" ] (eval.config.flake-file.description or "");
        inputsBody = nixCode {
          expr = resolvedInputs;
          styles = [ { attrSep = "\n    "; } { attrSep = "\n      "; } ];
        };
      in
      ''
        # Generated by two-phase-flake. Regen with: nix run .#bootstrap
        {
          description = "${desc}";
          outputs = ${builtins.readFile ./outputs-expr.nix};
          inputs = ${inputsBody};
        }
      '';

    eachSystem = lib.genAttrs [
      "x86_64-linux"
      "aarch64-linux"
      "x86_64-darwin"
      "aarch64-darwin"
    ];

    bootstrapApp = system:
      let
        pkgs = inputs.nixpkgs.legacyPackages.${system};
        flakeFile = pkgs.writeText "flake-source.nix" flakeSource;
      in
      {
        type = "app";
        program = lib.getExe (pkgs.writeShellApplication {
          name = "bootstrap";
          runtimeInputs = [ pkgs.nixfmt-rfc-style ];
          text = ''
            cp ${flakeFile} flake.nix
            nixfmt flake.nix
            echo "flake.nix materialized. Next: nix flake lock"
          '';
        });
      };
  in
  moduleOutputs // {
    apps = lib.recursiveUpdate (moduleOutputs.apps or { }) (
      eachSystem (system: { bootstrap = bootstrapApp system; })
    );
  }
