# The seed flake — copy this to flake.nix to start from scratch.
# Only needs nixpkgs + import-tree + flake-file. Running `nix run .#bootstrap`
# materializes a full flake.nix with all inputs declared by the module tree.
{
  description = "Two-phase flake: synthetic thin eval collects inputs, bootstrap materializes a real flake";

  inputs = {
    nixpkgs.url = "github:nixos/nixpkgs/nixpkgs-unstable";
    import-tree = {
      url = "github:vic/import-tree";
      flake = false;
    };
    flake-file.url = "github:vic/flake-file";
  };

  outputs =
    { nixpkgs, import-tree, flake-file, self, ... }@inputs:
    let
      inherit (nixpkgs) lib;
      importTree = import import-tree;

      # Thin eval: synthetic flake-file evaluation that only forces
      # flake-file.inputs (pure data). Outputs stay as thunks.
      thinEval = lib.evalModules {
        modules = [
          flake-file.flakeModules.flake
          (importTree ./modules)
        ];
      };

      cfg = thinEval.config;

      # Which declared inputs are missing from our actual flake inputs?
      declaredNames = builtins.attrNames cfg.flake-file.inputs;
      missingInputs = builtins.filter (n: !(inputs ? ${n})) declaredNames;
      allSatisfied = missingInputs == [ ];

      # Use flake-file's lib to render the resolved inputs as Nix source
      flakeFileLib = import "${flake-file}/dev/modules/_lib" lib;
      inherit (flakeFileLib) inputsExpr nixCode;

      resolvedInputs = cfg.flake-file.preProcess (inputsExpr cfg.flake-file.inputs);

      outputsExpr = builtins.readFile ./outputs-expr.nix;

      flakeSource = ''
        # Generated by two-phase-flake. Regen with: nix run .#bootstrap
        {
          description = "${lib.escape [ "\"" "\\" ] (cfg.flake-file.description or "")}";

          outputs = ${outputsExpr};

          inputs = ${
            nixCode {
              expr = resolvedInputs;
              styles = [
                { attrSep = "\n    "; }
                { attrSep = "\n      "; }
              ];
            }
          };
        }
      '';

      eachSystem = lib.genAttrs [
        "x86_64-linux"
        "aarch64-linux"
        "x86_64-darwin"
        "aarch64-darwin"
      ];

      bootstrapApp =
        system:
        let
          pkgs = nixpkgs.legacyPackages.${system};
          flakeFile = pkgs.writeText "flake-source.nix" flakeSource;
        in
        {
          type = "app";
          program = lib.getExe (pkgs.writeShellApplication {
            name = "bootstrap";
            runtimeInputs = [ pkgs.nixfmt-rfc-style ];
            text = ''
              cp ${flakeFile} flake.nix
              nixfmt flake.nix
              echo "flake.nix materialized with inputs: ${lib.concatStringsSep ", " declaredNames}"
              echo "Next: nix flake lock"
            '';
          });
        };

      # Phase 2: full eval with all inputs
      fullEval = lib.evalModules {
        specialArgs = {
          inherit inputs;
          inherit (inputs) self;
        };
        modules = [
          flake-file.flakeModules.flake
          (importTree ./modules)
        ];
      };

      moduleOutputs = fullEval.config.flake-outputs;

    in
    if allSatisfied then
      moduleOutputs
      // {
        apps = lib.recursiveUpdate (moduleOutputs.apps or { }) (
          eachSystem (system: { bootstrap = bootstrapApp system; })
        );
      }
    else
      {
        apps = eachSystem (system: {
          default = bootstrapApp system;
          bootstrap = bootstrapApp system;
        });
        missing = missingInputs;
      };
}
