# Render a complete flake.nix source from collected input specs.
{
  lib,
  seedInputs,
  extraInputs,
  outputsExpr,
  description ? "",
}:
let
  allInputs = seedInputs // extraInputs;

  # Minimal Nix value -> source code renderer
  renderNix =
    indent: value:
    if builtins.isString value then
      ''"${lib.escape [ "\"" "\\" "\$" ] value}"''
    else if builtins.isBool value then
      (if value then "true" else "false")
    else if builtins.isInt value then
      toString value
    else if builtins.isList value then
      "[ ${lib.concatMapStringsSep " " (renderNix indent) value} ]"
    else if builtins.isAttrs value then
      renderAttrs indent value
    else
      toString value;

  renderAttrs =
    indent:
    attrs:
    let
      inner = indent + "  ";
      rendered = lib.concatStringsSep "\n${inner}" (
        lib.mapAttrsToList (k: v: "${escapeKey k} = ${renderNix inner v};") attrs
      );
    in
    "{\n${inner}${rendered}\n${indent}}";

  escapeKey = k: if builtins.match "[a-zA-Z_][a-zA-Z0-9_'-]*" k != null then k else ''"${k}"'';

  # Render a single input entry, flattening simple follows
  renderInput =
    name: spec:
    let
      # Extract the fields we care about
      url = spec.url or "";
      flake = spec.flake or true;
      follows = spec.follows or null;
      subInputs = spec.inputs or { };

      # Build the attribute set to render
      attrs =
        (lib.optionalAttrs (url != "") { inherit url; })
        // (lib.optionalAttrs (!flake) { flake = false; })
        // (lib.optionalAttrs (follows != null) { inherit follows; })
        // (lib.optionalAttrs (subInputs != { }) { inputs = renderSubInputs subInputs; });

      # For simple url-only inputs, use flat syntax
      isSimple = url != "" && flake && follows == null && subInputs == { };
    in
    if isSimple then
      ''${escapeKey name}.url = "${lib.escape [ "\"" "\\" ] url}";''
    else
      "${escapeKey name} = ${renderNix "    " attrs};";

  # Render sub-input follows (e.g., inputs.nixpkgs.follows = "nixpkgs")
  renderSubInputs =
    subInputs:
    lib.mapAttrs (
      _: sub:
      if builtins.isString sub then
        { follows = sub; }
      else if sub ? follows && builtins.attrNames sub == [ "follows" ] then
        sub
      else
        sub
    ) subInputs;

  # Flatten sub-inputs into dotted notation for readability
  renderInputFlat =
    name: spec:
    let
      url = spec.url or "";
      flake = spec.flake or true;
      follows = spec.follows or null;
      subInputs = spec.inputs or { };

      lines =
        (lib.optional (url != "") ''${escapeKey name}.url = "${lib.escape [ "\"" "\\" ] url}";'')
        ++ (lib.optional (!flake) "${escapeKey name}.flake = false;")
        ++ (lib.optional (follows != null) ''${escapeKey name}.follows = "${follows}";'')
        ++ (lib.concatLists (
          lib.mapAttrsToList (
            subName: sub:
            let
              f = sub.follows or (if builtins.isString sub then sub else null);
            in
            lib.optional (f != null) ''${escapeKey name}.inputs.${escapeKey subName}.follows = "${f}";''
          ) subInputs
        ));
    in
    lib.concatStringsSep "\n    " lines;

  inputLines = lib.concatStringsSep "\n    " (
    lib.mapAttrsToList renderInputFlat allInputs
  );

  descLine = lib.optionalString (description != "") ''
    description = "${lib.escape [ "\"" "\\" ] description}";

  '';
in
''
  # Generated by two-phase-flake bootstrap. Regen with: nix run .#bootstrap
  {
    ${descLine}outputs =
      ${outputsExpr};

    inputs = {
      ${inputLines}
    };
  }
''
